# Generated by Django 4.1.3 on 2022-11-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('id_rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastFoodApp.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField()),
                ('estado', models.BooleanField()),
                ('id_detalle_pedido', models.ManyToManyField(through='FastFoodApp.Detalle_pedido', to='FastFoodApp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastFoodApp.menu')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastFoodApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='id_menu_producto',
            field=models.ManyToManyField(through='FastFoodApp.Menu_producto', to='FastFoodApp.producto'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastFoodApp.menu'),
        ),
        migrations.AddField(
            model_name='detalle_pedido',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FastFoodApp.pedido'),
        ),
    ]
