# Generated by Django 4.1.2 on 2022-12-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FastFoodApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="id_detalle_pedido",
        ),
        migrations.AddField(
            model_name="pedido",
            name="menus",
            field=models.ManyToManyField(to="FastFoodApp.menu"),
        ),
        migrations.DeleteModel(
            name="Detalle_pedido",
        ),
    ]
