# Generated by Django 4.1.3 on 2022-11-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FastFoodApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='id_menu_producto',
        ),
        migrations.AddField(
            model_name='menu',
            name='productos',
            field=models.ManyToManyField(to='FastFoodApp.producto'),
        ),
        migrations.DeleteModel(
            name='Menu_producto',
        ),
    ]
