# Generated by Django 4.1.2 on 2022-12-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FastFoodApp", "0003_remove_pedido_menus_alter_pedido_fecha_emision_orden"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orden",
            options={"verbose_name_plural": "Ordenes"},
        ),
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.BooleanField(default=False),
        ),
    ]
